{{- if .Values.jobs }}
{{- $defaultImage := include "flaskapp.image" . }}
{{- $labels := include "flaskapp.labels" . }}
{{- range .Values.jobs }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: cronjob
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            {{- if .image }}
            image: {{ .image }}
            {{- else }}
            image: {{ $defaultImage }}
            {{- end }}
            command:
              {{- toYaml .command | nindent 14 }}
          restartPolicy: OnFailure

{{- end }}
{{- end }}
