{{- $secretName := include "flaskapp.name" . -}}
{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "flaskapp.fullname" . }}-migrations
  labels:
    app: {{ template "flaskapp.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: migrations
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    metadata:
      name: {{ template "flaskapp.name" . }}-migrations
      labels:
        app: {{ template "flaskapp.name" . }}
        release: "{{ .Release.Name }}"
        component: migrations
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
      - name: {{ template "flaskapp.name" . }}-migrations
        image: {{ template "flaskapp.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.environmentVariables }}
        env:
        {{- range .Values.environmentVariables }}
          - name: {{ .name }}
            {{- if .value }}
            value: "{{ .value }}"
            {{- end }}
            {{- if .valueFromSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ $secretName }}
                key: {{ .valueFromSecret }}
            {{- end }}
        {{- end }}
        {{- end }}
        command: {{ tpl .Values.migration.command . }}
      restartPolicy: OnFailure
{{- end }}
