{{- $secretName := include "flaskapp.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskapp.fullname" . }}
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flaskapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "flaskapp.labels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      {{- include "flaskapp.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: app
          image: {{ template "flaskapp.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          {{- if .Values.image.command }}
          command: 
            {{- toYaml .Values.image.command | nindent 12 -}}
          {{- end -}}
          {{- include "flaskapp.env" . | nindent 10 -}}
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.liveness }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.readiness }}
              port: http
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- tpl .Values.volumeMounts . | nindent 12 }}
          {{- end }}
        {{- if .Values.extraContainers }}
        {{- tpl .Values.extraContainers . | nindent 8}}
        {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{ tpl .Values.initContainers . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{ tpl .Values.volumes . | nindent 8 }}
      {{- end }}
