{{- $fullName := include "flaskapp.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- if . }}
            path: {{ . }}
          {{- end }}
        {{- end }}
  {{- end }}
