{{- $fullName := include "flaskapp.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    helm.sh/chart: {{ include "flaskapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  # annotations:
    # kubernetes.io/tls-acme: "true"
    # certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- if . }}
            path: {{ . }}
          {{- end }}
        {{- end }}
  {{- end }}
