{{- if .Values.image.dockerConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaskapp.name" . }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.dockerConfig | b64enc }} 
{{- end -}}
---

{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaskapp.name" . }}
  labels:
    app: {{ include "flaskapp.name" . }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{ .name }}: "{{ .value | b64enc }}"
  {{- end }}
{{- end -}}
