{{- if .Values.image.dockerConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaskapp.name" . }}-regcred
  labels:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    helm.sh/chart: {{ include "flaskapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.dockerConfig | b64enc }} 
{{- end }}

---

{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaskapp.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    helm.sh/chart: {{ include "flaskapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ $value | b64enc }}"
  {{- end }}
{{- end -}}
