{{- $serviceType := "ClusterIP" }}
{{- $servicePort := 80 }}
{{- if .Values.service }}
{{- $serviceType = .Values.service.type }}
{{- $servicePort = .Values.service.port }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ $serviceType }}
  ports:
    - port: {{ $servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
