
{{- if .Values.celery.enabled }}
{{- if .Values.celery.beatCommand }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskapp.fullname" . }}-celery-beat
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flaskapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "flaskapp.labels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: {{ template "flaskapp.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          command: 
            {{- toYaml .Values.celery.beatCommand | nindent 12 -}}
          {{- include "flaskapp.env" . | nindent 10 -}}
      {{- include "flaskapp.imagePullSecrets" . | nindent 6 }}
{{- end }}
{{- end }}
