
{{- if .Values.celery.enabled }}
{{- if .Values.celery.beatCommand }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskapp.fullname" . }}-celery-beat
  labels:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    helm.sh/chart: {{ include "flaskapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flaskapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flaskapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: celery-beat
          image: {{ template "flaskapp.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          command: {{ tpl .Values.celery.beatCommand . }}
          {{ include "flaskapp.env" . | nindent 10 }}
      
      {{ include "flaskapp.imagePullSecrets" . | nindent 8 }}
{{- end }}

{{- end }}
