
{{- if .Values.celery.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskapp.fullname" . }}-celery-worker
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  replicas: {{ .Values.celery.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flaskapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "flaskapp.labels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: {{ template "flaskapp.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.celery.worker.port }}
              protocol: TCP
          command: 
            {{- toYaml .Values.celery.worker.command | nindent 12 -}}
          {{- include "flaskapp.env" . | nindent 10 -}}
{{- end }}